# Generated by Django 3.2.11 on 2022-01-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contact_us'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Us',
            new_name='Contact',
        ),
    ]
